import { PencilSimple } from "@phosphor-icons/react";
import { useCallback, useDeferredValue, useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import type { AcademicClass, ClassForm, ClassStatus, Course, Page } from "../academic-types";
import { classEmpty, classStatusLabel, date } from "../academic-types";
import { Drawer, LoadState, PageHeader, PrimaryAction, SearchField, StatusBadge } from "../components/AdminUi";
import { apiFetch } from "../lib/api";

export function ClassesPage() {
  const [items, setItems] = useState<AcademicClass[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [courseId, setCourseId] = useState("all"); const [editing, setEditing] = useState<AcademicClass | null>(null); const [form, setForm] = useState<ClassForm>(classEmpty); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const deferredQuery = useDeferredValue(query);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ size: "100" }); if (courseId !== "all") params.set("courseId", courseId); else if (status !== "all") params.set("status", status); const [classPage, coursePage] = await Promise.all([apiFetch<Page<AcademicClass>>(`/admin/classes?${params}`), apiFetch<Page<Course>>("/admin/courses?size=100&active=true")]); setItems(classPage.content); setCourses(coursePage.content); } catch (value) { setError(value instanceof Error ? value.message : "Không tải được lớp học"); } finally { setLoading(false); } }, [courseId, status]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => items.filter(item => `${item.code} ${item.name}`.toLowerCase().includes(deferredQuery.toLowerCase()) && (status === "all" || item.status === status)), [items, deferredQuery, status]);
  const courseName = (id: string) => courses.find(item => item.id === id)?.name ?? "Khóa học không xác định";
  function create() { setEditing(null); setForm({ ...classEmpty, courseId: courses[0]?.id ?? "" }); setOpen(true); }
  function edit(item: AcademicClass) { setEditing(item); setForm({ courseId: item.courseId, code: item.code, name: item.name, capacity: String(item.capacity), startsOn: item.startsOn, endsOn: item.endsOn ?? "", status: item.status, defaultZoomUrl: item.defaultZoomUrl ?? "" }); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const body = { name: form.name, capacity: Number(form.capacity), startsOn: form.startsOn, endsOn: form.endsOn || null, status: form.status, defaultZoomUrl: form.defaultZoomUrl || null }; try { if (editing) await apiFetch(`/admin/classes/${editing.id}`, { method: "PUT", body: JSON.stringify(body) }); else await apiFetch("/admin/classes", { method: "POST", body: JSON.stringify({ courseId: form.courseId, code: form.code, ...body }) }); setOpen(false); await load(); } catch (value) { setError(value instanceof Error ? value.message : "Không thể lưu lớp học"); } finally { setSaving(false); } }
  const field = (key: keyof ClassForm) => ({ value: form[key], onChange: (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value }) });
  return <section><PageHeader eyebrow="Tổ chức đào tạo" title="Quản lý lớp học" description="Theo dõi kỳ học, sức chứa, tiến độ vận hành và đường dẫn Zoom mặc định." action={<PrimaryAction onClick={create}>Thêm lớp học</PrimaryAction>} />
    <div className="admin-toolbar"><SearchField value={query} onChange={setQuery} placeholder="Tìm mã hoặc tên lớp" /><label><span>Khóa học</span><select value={courseId} onChange={event => setCourseId(event.target.value)}><option value="all">Tất cả khóa học</option>{courses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Trạng thái</span><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">Tất cả</option>{Object.entries(classStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <LoadState loading={loading} error={error} empty={!visible.length} onRetry={() => void load()} />
    {!loading && !error && visible.length > 0 && <div className="admin-table-wrap"><table className="academic-table"><thead><tr><th>Lớp học</th><th>Khóa học</th><th>Thời gian</th><th>Sức chứa</th><th>Trạng thái</th><th>Zoom</th><th>Thao tác</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><strong>{item.name}</strong><span>{item.code}</span></td><td>{courseName(item.courseId)}</td><td><strong>{date(item.startsOn)}</strong><span>đến {date(item.endsOn)}</span></td><td className="data-number">{item.capacity}</td><td><StatusBadge value={item.status}>{classStatusLabel[item.status]}</StatusBadge></td><td>{item.defaultZoomUrl ? <a href={item.defaultZoomUrl} target="_blank" rel="noreferrer">Mở link</a> : "Chưa có"}</td><td><div className="row-actions"><button aria-label={`Sửa ${item.name}`} onClick={() => edit(item)}><PencilSimple /></button></div></td></tr>)}</tbody></table></div>}
    {open && <Drawer title={editing ? "Cập nhật lớp học" : "Thêm lớp học"} description="Một lớp luôn thuộc một khóa học và có chu kỳ vận hành riêng." onClose={() => setOpen(false)}><form className="admin-form" onSubmit={save}><label>Khóa học<select required disabled={!!editing} {...field("courseId")}><option value="">Chọn khóa học</option>{courses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="form-columns"><label>Mã lớp<input required disabled={!!editing} {...field("code")} /></label><label>Sức chứa<input required type="number" min="1" {...field("capacity")} /></label></div><label>Tên lớp<input required {...field("name")} /></label><div className="form-columns"><label>Ngày bắt đầu<input required type="date" {...field("startsOn")} /></label><label>Ngày kết thúc<input type="date" {...field("endsOn")} /></label></div><label>Trạng thái<select {...field("status")}>{Object.entries(classStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Link Zoom mặc định<input type="url" {...field("defaultZoomUrl")} placeholder="https://zoom.us/j/..." /></label>{error && <p className="form-error" role="alert">{error}</p>}<footer><button type="button" className="admin-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="admin-primary" disabled={saving}>{saving ? "Đang lưu..." : "Lưu lớp học"}</button></footer></form></Drawer>}
  </section>;
}
