import { BookOpenText, PencilSimple, Power, Trash } from "@phosphor-icons/react";
import { useCallback, useDeferredValue, useEffect, useMemo, useState, type FormEvent } from "react";
import type { Course, CourseForm, Page } from "../academic-types";
import { courseEmpty, money } from "../academic-types";
import { Drawer, LoadState, PageHeader, PrimaryAction, SearchField, StatusBadge } from "../components/AdminUi";
import { apiFetch } from "../lib/api";

export function CoursesPage() {
  const [items, setItems] = useState<Course[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [active, setActive] = useState("all"); const [editing, setEditing] = useState<Course | null>(null); const [form, setForm] = useState<CourseForm>(courseEmpty); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const deferredQuery = useDeferredValue(query);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const suffix = active === "all" ? "" : `&active=${active}`; const page = await apiFetch<Page<Course>>(`/admin/courses?size=100${suffix}`); setItems(page.content); } catch (value) { setError(value instanceof Error ? value.message : "Không tải được khóa học"); } finally { setLoading(false); } }, [active]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => items.filter(item => `${item.code} ${item.name} ${item.level ?? ""}`.toLowerCase().includes(deferredQuery.toLowerCase())), [items, deferredQuery]);
  function create() { setEditing(null); setForm(courseEmpty); setOpen(true); }
  function edit(item: Course) { setEditing(item); setForm({ code: item.code, name: item.name, description: item.description ?? "", level: item.level ?? "", targetBand: item.targetBand?.toString() ?? "", totalSessions: item.totalSessions?.toString() ?? "", tuitionAmount: item.tuitionAmount?.toString() ?? "", isPublic: item.isPublic, isActive: item.isActive }); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const body = { name: form.name, description: form.description || null, level: form.level || null, targetBand: form.targetBand ? Number(form.targetBand) : null, totalSessions: form.totalSessions ? Number(form.totalSessions) : null, tuitionAmount: form.tuitionAmount ? Number(form.tuitionAmount) : null, isPublic: form.isPublic, isActive: form.isActive }; try { if (editing) await apiFetch(`/admin/courses/${editing.id}`, { method: "PUT", body: JSON.stringify(body) }); else await apiFetch("/admin/courses", { method: "POST", body: JSON.stringify({ code: form.code, ...body }) }); setOpen(false); await load(); } catch (value) { setError(value instanceof Error ? value.message : "Không thể lưu khóa học"); } finally { setSaving(false); } }
  async function deactivate(item: Course) { if (!window.confirm(`Ngừng hoạt động khóa học ${item.name}?`)) return; try { await apiFetch(`/admin/courses/${item.id}`, { method: "DELETE" }); await load(); } catch (value) { setError(value instanceof Error ? value.message : "Không thể ngừng khóa học"); } }
  const field = (key: keyof CourseForm) => ({ value: String(form[key] ?? ""), onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [key]: event.target.value }) });
  return <section><PageHeader eyebrow="Học vụ" title="Quản lý khóa học" description="Thiết lập chương trình, band mục tiêu, học phí và trạng thái công khai." action={<PrimaryAction onClick={create}>Thêm khóa học</PrimaryAction>} />
    <div className="admin-toolbar"><SearchField value={query} onChange={setQuery} placeholder="Tìm theo mã, tên hoặc trình độ" /><label><span>Trạng thái</span><select value={active} onChange={event => setActive(event.target.value)}><option value="all">Tất cả</option><option value="true">Đang hoạt động</option><option value="false">Ngừng hoạt động</option></select></label></div>
    <LoadState loading={loading} error={error} empty={!visible.length} onRetry={() => void load()} />
    {!loading && !error && visible.length > 0 && <div className="admin-table-wrap"><table className="academic-table"><thead><tr><th>Khóa học</th><th>Trình độ</th><th>Band mục tiêu</th><th>Thời lượng</th><th>Học phí</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><strong>{item.name}</strong><span>{item.code}</span></td><td>{item.level || "Chưa đặt"}</td><td className="data-number">{item.targetBand ?? "–"}</td><td>{item.totalSessions ? `${item.totalSessions} buổi` : "Chưa đặt"}</td><td>{money(item.tuitionAmount)}</td><td><StatusBadge value={item.isActive ? "active" : "inactive"}>{item.isActive ? "Hoạt động" : "Ngừng hoạt động"}</StatusBadge></td><td><div className="row-actions"><button aria-label={`Sửa ${item.name}`} onClick={() => edit(item)}><PencilSimple /></button>{item.isActive && <button className="danger" aria-label={`Ngừng ${item.name}`} onClick={() => void deactivate(item)}><Power /></button>}</div></td></tr>)}</tbody></table></div>}
    {open && <Drawer title={editing ? "Cập nhật khóa học" : "Thêm khóa học"} description="Thông tin được dùng xuyên suốt trong lớp học và tuyển sinh." onClose={() => setOpen(false)}><form className="admin-form" onSubmit={save}><label>Mã khóa học<input required disabled={!!editing} {...field("code")} /></label><label>Tên khóa học<input required {...field("name")} /></label><div className="form-columns"><label>Trình độ<input {...field("level")} placeholder="Foundation, 6.5+..." /></label><label>Band mục tiêu<input type="number" min="0" max="9" step="0.5" {...field("targetBand")} /></label><label>Tổng số buổi<input type="number" min="1" {...field("totalSessions")} /></label><label>Học phí<input type="number" min="0" {...field("tuitionAmount")} /></label></div><label>Mô tả<textarea rows={5} {...field("description")} /></label><div className="toggle-row"><label><input type="checkbox" checked={form.isPublic} onChange={event => setForm({ ...form, isPublic: event.target.checked })} />Công khai trên website</label>{editing && <label><input type="checkbox" checked={form.isActive} onChange={event => setForm({ ...form, isActive: event.target.checked })} />Đang hoạt động</label>}</div>{error && <p className="form-error" role="alert">{error}</p>}<footer><button type="button" className="admin-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="admin-primary" disabled={saving}>{saving ? "Đang lưu..." : "Lưu khóa học"}</button></footer></form></Drawer>}
  </section>;
}
