/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#efedf5",
        "on-background": "#1b1b21",
        "surface-dim": "#dbd9e1",
        "primary-fixed-dim": "#ffb1c2",
        "surface-container-highest": "#e3e1ea",
        "secondary-fixed": "#ffd9e0",
        "on-secondary-fixed": "#3f0018",
        "on-tertiary-fixed-variant": "#594400",
        "on-primary-fixed": "#380a19",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#6d3544",
        "secondary-container": "#fe8fab",
        "primary": "#894c5b",
        "on-surface-variant": "#524346",
        "outline-variant": "#d6c2c4",
        "on-surface": "#1b1b21",
        "on-secondary": "#ffffff",
        "secondary": "#9b3f5a",
        "surface-container-high": "#e9e7f0",
        "surface": "#fbf8ff",
        "on-primary-container": "#67303f",
        "primary-fixed": "#ffd9df",
        "primary-container": "#e49aaa",
        "inverse-surface": "#2f3036",
        "surface-bright": "#fbf8ff",
        "surface-container-low": "#f5f2fb",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#eec140",
        "inverse-primary": "#ffb1c2",
        "outline": "#847375",
        "on-secondary-fixed-variant": "#7d2843",
        "inverse-on-surface": "#f2eff8",
        "tertiary-fixed": "#ffdf92",
        "tertiary-container": "#d4a929",
        "secondary-fixed-dim": "#ffb1c2",
        "tertiary": "#765b00",
        "on-tertiary-fixed": "#241a00",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e3e1ea",
        "on-secondary-container": "#78243f",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#533f00",
        "on-error-container": "#93000a",
        "background": "#fbf8ff",
        "surface-tint": "#894c5b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "sm": "16px",
        "md": "24px",
        "margin-mobile": "16px",
        "base": "4px",
        "lg": "40px",
        "xs": "8px",
        "margin-desktop": "80px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Be Vietnam Pro"],
        "label-md": ["Be Vietnam Pro"],
        "caption": ["Be Vietnam Pro"],
        "display": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Be Vietnam Pro"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
